// =========================================================================
// 初期データ（つるるんとん 固定設定）
// 販売版では、この塊を店舗ごとに差し替えるだけで汎用化できる設計。
// =========================================================================

import {
  BackgroundPlate,
  BrandLedger,
  SafeTemplate,
  StoryInput,
  TextDesign,
  TextMode,
} from "./types";

// ---- ブランド台帳 -----------------------------------------------------

export const SEED_BRAND: BrandLedger = {
  store: {
    name: "美肌理容室つるるんとん",
    industry: "理容室・メンズ美容",
    storeType: "夫婦経営",
    customers:
      "男性、清潔感を整えたい方、髪・肌・ヒゲ・疲れ・見た目の印象に悩みがある方",
    atmosphere: "個室、落ち着く、あたたかい、親しみやすい、癒される",
    tagline: "男性が清潔感と自信を取り戻す場所",
  },
  core: [
    "見た目を整えるだけでなく、心も少し軽くなって帰ってほしい。",
    "男性が髪・肌・ヒゲの悩みを安心して話せる場所。",
    "夫婦であたたかく迎え、愛犬ロナが言葉では届かない部分を癒す。",
    "お客様が帰る時に「また明日も少し頑張れそう」と思える世界観にする。",
  ].join("\n"),
  characters: [
    {
      id: "tsuru",
      name: "つる君",
      role: "技術で整える人",
      personality: "落ち着いている、安心感がある、観察力がある、職人らしい",
      storyRole: "カットや施術を通して、お客様の外見と心の輪郭を整える",
      emoji: "✂️",
    },
    {
      id: "run",
      name: "るんちゃん",
      role: "心をほどく人",
      personality: "やさしい、言葉で包む、本音を引き出す、気づきを与える",
      storyRole: "お客様の愚痴や不安を受け止め、少しずつ心を軽くする",
      emoji: "🌸",
    },
    {
      id: "rona",
      name: "ロナ",
      role: "言葉なしで癒す存在",
      personality: "無邪気、安心感、少し笑い、場をゆるめる",
      storyRole: "重くなりすぎた場面をやわらげる。最後の余韻や癒しに使う",
      emoji: "🐶",
    },
  ],
  menu: {
    name: "【美肌極み】",
    content:
      "カット、お顔剃り、お顔の毛穴洗浄、極みヘッドスパがセットになった看板メニュー",
    steps: [
      {
        id: "cut",
        name: "カット",
        meaning: "外見の輪郭が整い始める。第一印象が変わる。",
        emoji: "✂️",
      },
      {
        id: "shave",
        name: "お顔剃り",
        meaning: "表情がやわらぎ、張りつめていたものがほどける。",
        emoji: "🪒",
      },
      {
        id: "pore",
        name: "お顔の毛穴洗浄",
        meaning: "顔の汚れだけでなく、心の詰まりやモヤモヤも流れるように感じる。",
        emoji: "💧",
      },
      {
        id: "spa",
        name: "極みヘッドスパ",
        meaning: "頭の中の重さがほどけ、本音や気づきが出やすくなる。",
        emoji: "🌿",
      },
      {
        id: "mirror",
        name: "鏡を見る",
        meaning: "整った自分を見て、少し前を向く。",
        emoji: "🪞",
      },
      {
        id: "leave",
        name: "帰り際",
        meaning: "また明日も少し頑張れそうと思える。",
        emoji: "🌅",
      },
    ],
  },
  rules: [
    "1話完結型。重くなりすぎず、最後は静かに前向きに終える。",
    "つる君＝技術で外見と心の輪郭を整える。説教はしない。",
    "るんちゃん＝言葉で本音をほどく。否定せず受け止める。",
    "ロナ＝言葉なしで場をやわらげる。出すぎず、余韻として効かせる。",
    "悩み→施術の心の変化→小さな気づき→前向き、の流れを守る。",
    "誇大表現・断定表現は使わない（治る/必ず/絶対 などは禁止）。",
  ],
};

// ---- 背景プレート（固定資産・第一弾は仮プレート） ----------------------

export const SEED_BACKGROUNDS: BackgroundPlate[] = [
  {
    id: "bg-gaikan",
    name: "外観",
    scene: "オープニング／お店の紹介",
    chairDirection: "—",
    hasMirror: false,
    difficulty: "low",
    allowedCompositions: ["引きの全景", "看板を中心に", "やわらかい朝の光"],
    forbiddenCompositions: ["人物の顔アップ", "店内の細部"],
    allowedProps: ["小さな植木", "暖簾", "ロナの足あと"],
    forbiddenProps: ["車", "通行人の群衆", "実在の地名看板"],
    hue: "35",
    hasImage: false,
  },
  {
    id: "bg-iriguchi",
    name: "入口",
    scene: "来店／お出迎え",
    chairDirection: "ドアに向かって正面",
    hasMirror: false,
    difficulty: "low",
    allowedCompositions: ["お出迎えの2人", "ドア越しのあたたかい光"],
    forbiddenCompositions: ["施術中の様子", "鏡の反射"],
    allowedProps: ["スリッパ", "観葉植物", "ロナ"],
    forbiddenProps: ["施術道具", "他のお客様"],
    hue: "28",
    hasImage: false,
  },
  {
    id: "bg-cut-front",
    name: "カット椅子正面",
    scene: "カット工程",
    chairDirection: "正面（鏡に向かう）",
    hasMirror: true,
    difficulty: "mid",
    allowedCompositions: ["背後からのカット", "肩より上の構図", "落ち着いた表情中心"],
    forbiddenCompositions: ["鏡の反射を主役にする", "ハサミの刃のアップ"],
    allowedProps: ["ケープ", "くし", "やわらかい照明"],
    forbiddenProps: ["背景にない棚や家具", "強い刃物の強調"],
    hue: "200",
    hasImage: false,
  },
  {
    id: "bg-cut-angle",
    name: "カット椅子斜め",
    scene: "カット工程（表情を見せる）",
    chairDirection: "斜め45度",
    hasMirror: true,
    difficulty: "mid",
    allowedCompositions: ["斜め前からの安心した表情", "つる君の手元はやわらかく"],
    forbiddenCompositions: ["鏡像と本人の二重写り", "刃物アップ"],
    allowedProps: ["ケープ", "くし"],
    forbiddenProps: ["背景にない家具", "鋭い金属の強調"],
    hue: "190",
    hasImage: false,
  },
  {
    id: "bg-mirror",
    name: "鏡前",
    scene: "鏡を見る／変化を実感",
    chairDirection: "正面（鏡に向かう）",
    hasMirror: true,
    difficulty: "high",
    allowedCompositions: ["本人の表情を中心に", "鏡はやわらかいボケ"],
    forbiddenCompositions: ["鏡の反射を主役にする", "鏡像と本人で顔が食い違う"],
    allowedProps: ["やわらかい照明", "鏡のフレーム"],
    forbiddenProps: ["反射に映る別人", "背景にない物"],
    hue: "210",
    hasImage: false,
  },
  {
    id: "bg-shave",
    name: "顔剃りスペース",
    scene: "お顔剃り工程",
    chairDirection: "リクライニング（やや後傾）",
    hasMirror: false,
    difficulty: "high",
    allowedCompositions: ["お客様の安心した表情を中心", "手元はやわらかく抽象的に"],
    forbiddenCompositions: ["カミソリの刃のアップ", "手元のクローズアップ強調"],
    allowedProps: ["蒸しタオル", "やわらかい泡（控えめ）"],
    forbiddenProps: ["刃物の強調", "血や赤みの演出", "背景にない器具"],
    hue: "150",
    hasImage: false,
  },
  {
    id: "bg-pore",
    name: "毛穴洗浄スペース",
    scene: "お顔の毛穴洗浄工程",
    chairDirection: "リクライニング（やや後傾）",
    hasMirror: false,
    difficulty: "mid",
    allowedCompositions: ["流れる水のやわらかい表現", "ほどけていく表情"],
    forbiddenCompositions: ["毛穴の拡大描写", "肌トラブルの強調"],
    allowedProps: ["やわらかい水しぶき", "蒸しタオル"],
    forbiddenProps: ["医療機器に見える器具", "背景にない設備"],
    hue: "175",
    hasImage: false,
  },
  {
    id: "bg-spa",
    name: "極みヘッドスパスペース",
    scene: "極みヘッドスパ工程",
    chairDirection: "フルリクライニング",
    hasMirror: false,
    difficulty: "mid",
    allowedCompositions: ["頭の重さがふわっと軽くなる抽象表現", "やすらいだ表情"],
    forbiddenCompositions: ["指圧の力強さ強調", "顔のアップで力み"],
    allowedProps: ["ふわっとした光の粒", "やわらかい泡（控えめ）"],
    forbiddenProps: ["背景にない家具", "強い色のボトル群"],
    hue: "120",
    hasImage: false,
  },
  {
    id: "bg-shampoo",
    name: "シャンプー椅子",
    scene: "シャンプー／洗髪",
    chairDirection: "後傾（首は無理のない角度）",
    hasMirror: false,
    difficulty: "high",
    allowedCompositions: ["椅子の向きに合わせる", "首の角度は自然に", "泡は控えめ"],
    forbiddenCompositions: ["首を強く反らせる", "泡をつけすぎる", "不自然な体勢"],
    allowedProps: ["やわらかい泡（控えめ）", "蒸しタオル"],
    forbiddenProps: ["背景にないシンク以外の設備", "水の飛沫の過剰演出"],
    hue: "195",
    hasImage: false,
  },
  {
    id: "bg-rona",
    name: "ロナがいる場所",
    scene: "余韻／癒し",
    chairDirection: "—",
    hasMirror: false,
    difficulty: "low",
    allowedCompositions: ["足元や近くで安心感を出す", "小さく添える"],
    forbiddenCompositions: ["ロナを主役で大きく", "施術の邪魔に見える配置"],
    allowedProps: ["クッション", "やわらかい毛布", "おもちゃ"],
    forbiddenProps: ["施術道具のそば", "背景にない家具"],
    hue: "45",
    hasImage: false,
  },
];

// ---- 安全構図テンプレート ---------------------------------------------

export const SEED_TEMPLATES: SafeTemplate[] = [
  {
    id: "tpl-shave",
    scene: "顔剃り",
    difficulty: "high",
    rules: [
      "手元をアップにしない",
      "カミソリを強調しない",
      "お客様の安心した表情を中心にする",
    ],
    recommendedComposition:
      "顔のやわらかい表情をやや上から。手元と道具は画面のすみで抽象的に。",
    emoji: "🪒",
  },
  {
    id: "tpl-shampoo",
    scene: "シャンプー椅子",
    difficulty: "high",
    rules: [
      "椅子の向きに合わせる",
      "首の角度を無理にしない",
      "泡をつけすぎない",
    ],
    recommendedComposition:
      "椅子のラインと体の向きをそろえ、首は自然な角度。泡は少量でやわらかく。",
    emoji: "🫧",
  },
  {
    id: "tpl-mirror",
    scene: "鏡シーン",
    difficulty: "high",
    rules: [
      "鏡の反射を主役にしない",
      "本人の表情を中心にする",
      "鏡像と本人の顔を食い違わせない",
    ],
    recommendedComposition:
      "本人の表情を主役に、鏡はやわらかいボケで添える。反射に人物を描き込みすぎない。",
    emoji: "🪞",
  },
  {
    id: "tpl-spa",
    scene: "ヘッドスパ",
    difficulty: "mid",
    rules: [
      "頭の重さがふわっと軽くなる抽象表現を使える",
      "指圧の力強さを強調しない",
      "やすらいだ表情を中心に",
    ],
    recommendedComposition:
      "ふわっとした光の粒や軽さの抽象表現。顔はやすらいだ表情で力みなく。",
    emoji: "🌿",
  },
  {
    id: "tpl-rona",
    scene: "ロナ",
    difficulty: "low",
    rules: [
      "足元や近くで安心感を出す",
      "小さく添える",
      "主役を奪わない",
    ],
    recommendedComposition: "画面のすみや足元に小さく。視線の先にそっと置く。",
    emoji: "🐶",
  },
];

// ---- 文字数・余白設計（モード別プリセット） ----------------------------

// charsPerPage が 160 以上だと「会話たっぷりの rich 版」、未満だと「短い lite 版」で生成される。
export const TEXT_MODE_PRESETS: Record<TextMode, Omit<TextDesign, "mode">> = {
  omakase: {
    totalChars: 2500,
    pages: 8,
    charsPerPage: 310,
    inImageTextChars: 12,
    postcardLineChars: 40,
    snsShortChars: 120,
    blogIntroChars: 240,
    instoreArtHasText: false,
    qrMargin: true,
  },
  short: {
    totalChars: 450,
    pages: 5,
    charsPerPage: 90,
    inImageTextChars: 8,
    postcardLineChars: 30,
    snsShortChars: 90,
    blogIntroChars: 130,
    instoreArtHasText: false,
    qrMargin: true,
  },
  standard: {
    totalChars: 2500,
    pages: 8,
    charsPerPage: 310,
    inImageTextChars: 12,
    postcardLineChars: 40,
    snsShortChars: 120,
    blogIntroChars: 240,
    instoreArtHasText: false,
    qrMargin: true,
  },
  deep: {
    totalChars: 3000,
    pages: 8,
    charsPerPage: 360,
    inImageTextChars: 14,
    postcardLineChars: 45,
    snsShortChars: 130,
    blogIntroChars: 340,
    instoreArtHasText: true,
    qrMargin: true,
  },
  sns: {
    totalChars: 420,
    pages: 5,
    charsPerPage: 84,
    inImageTextChars: 10,
    postcardLineChars: 35,
    snsShortChars: 140,
    blogIntroChars: 180,
    instoreArtHasText: false,
    qrMargin: false,
  },
  postcard: {
    totalChars: 500,
    pages: 5,
    charsPerPage: 100,
    inImageTextChars: 12,
    postcardLineChars: 50,
    snsShortChars: 120,
    blogIntroChars: 200,
    instoreArtHasText: false,
    qrMargin: true,
  },
  instore: {
    totalChars: 720,
    pages: 6,
    charsPerPage: 120,
    inImageTextChars: 16,
    postcardLineChars: 40,
    snsShortChars: 110,
    blogIntroChars: 200,
    instoreArtHasText: true,
    qrMargin: true,
  },
  imageheavy: {
    totalChars: 420,
    pages: 7,
    charsPerPage: 60,
    inImageTextChars: 10,
    postcardLineChars: 35,
    snsShortChars: 100,
    blogIntroChars: 150,
    instoreArtHasText: false,
    qrMargin: true,
  },
};

export const SEED_TEXT_DESIGN: TextDesign = {
  mode: "standard",
  ...TEXT_MODE_PRESETS.standard,
};

// ---- デモ用サンプルストーリーの入力（くま君） --------------------------
// 実体（StoryResult）は store 側で generateStory() を通して生成する。

export const SAMPLE_STORY_INPUT: StoryInput = {
  guestName: "大きな荷物を背負ったくま君",
  guestType: "くま",
  appearance: "大きな背中、少し疲れた目、丸い肩",
  personality: "がんばり屋、まじめ、人に頼るのが苦手",
  outerAttitude: "「大丈夫です」と笑ってしまう",
  realWorry: "家族にも職場にも弱音を吐けない",
  complaint: "最近、鏡を見るのもおっくうで…",
  complex: "顔が疲れて見えるのが気になる",
  visitReason: "顔が疲れて見えるのが気になる",
  finalRealization: "頼ることも優しさ",
  useRona: true,
  emphasizedStepId: "spa",
  mood: "静かに前向き",
  textMode: "standard",
};
